services:
  - type: web
    name: Shiva-Shine
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: ShivaShine
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: Shiva-Shine
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: psql
          name: shivashine-db
          property: host
      - key: DB_PORT
        fromService:
          type: psql
          name: shivashine-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: psql
          name: shivashine-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: psql
          name: shivashine-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: shivashine-db
          property: password

databases:
  - name: shivashine-db
    plan: free
    region: oregon
    databaseName: shivashine
    user: shivashine
