# Exported from Render on 2026-01-19T17:21:32Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Shiva-Shine
      runtime: docker
      repo: https://github.com/HetHingrajiya/Shiva-Shine
      plan: free
      region: oregon
      dockerContext: .
      dockerfilePath: .
      autoDeployTrigger: commit
