services:
  - type: web
    name: Shiva-Shine
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: ShivaShine
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://shiva-shine-1.onrender.com
      - key: APP_KEY
        value: base64:FPr4GnTMMdmaDjX8B1XL3wWYCamQirxwZlG3uj8oztI=
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d5ohbhf5c7fs73d4ah70-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: shivashinedb
      - key: DB_USERNAME
        value: shivashinedb_user
      - key: DB_PASSWORD
        value: Xdo2CRpb2C3kzb5yYXdh78scey9VVFI0
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: hemanglakhadiya49@gmail.com
      - key: MAIL_PASSWORD
        value: tstxtowtggisbvle
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: hemanglakhadiya49@gmail.com
      - key: MAIL_FROM_NAME
        value: Shiva Shine
      - key: GOOGLE_CLIENT_ID
        value: 951055380094-mp2scurmk4ehu9pb5e9p6tohorpqbsuk.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_REDIRECT
        value: https://shiva-shine-1.onrender.com/auth/google/callback
